"""Build the locked, source-derived vaccine fridge.

Geometry is authored in integer model pixels and divided by 32 at vertex
creation time.  The front, side and back skins are extracted from the locked
turnaround and resampled with nearest-neighbour filtering to the same model
pixel grid.  No UV projection or unwrap operator is used.
"""
from __future__ import annotations

from pathlib import Path
import json

import bmesh
import bpy


ROOT = Path(__file__).resolve().parents[2]
LOCK = ROOT / "docs" / "reference-lock" / "vaccine-fridge-v1"
AUTHORITY = json.loads((LOCK / "geometry-authority.json").read_text(encoding="utf-8"))
PPU = float(AUTHORITY["pixelsPerUnit"])
OUT = ROOT / "public" / "models" / "vaccine-fridge-source-true.glb"
ATLAS = ROOT / "public" / "textures" / "vaccine-fridge-source-atlas.png"
GLASS_OVERLAY = ROOT / "public" / "textures" / "vaccine-fridge-glass-reflection.png"
TOP_TEXTURE = ROOT / "public" / "textures" / "vaccine-fridge-top.png"
SHELF_TEXTURE = ROOT / "public" / "textures" / "vaccine-fridge-shelf.png"
HANDLE_TEXTURE = ROOT / "public" / "textures" / "vaccine-fridge-handle.png"
DISPLAY_TEXTURE = ROOT / "public" / "textures" / "vaccine-fridge-display.png"
GRILLE_TEXTURE = ROOT / "public" / "textures" / "vaccine-fridge-grille.png"
NANO_VERSION = "v5"
NANO_CREAM_TILE = ROOT / "public" / "textures" / f"vaccine-fridge-nano-cream-microtile-{NANO_VERSION}.png"
NANO_STEEL_TILE = ROOT / "public" / "textures" / f"vaccine-fridge-nano-steel-microtile-{NANO_VERSION}.png"
NANO_STEEL_PANEL_TILE = ROOT / "public" / "textures" / f"vaccine-fridge-nano-steel-panel-microtile-{NANO_VERSION}.png"
NANO_TEAL_TILE = ROOT / "public" / "textures" / f"vaccine-fridge-nano-teal-microtile-{NANO_VERSION}.png"
NANO_AUDIT = LOCK / "nano-banana-v5" / "nano-reference-material-primitives-v5.audit.json"
NANO_DECAL_ATLAS = ROOT / "public" / "textures" / "vaccine-fridge-nano-decals-v6.png"
NANO_DECAL_AUDIT = LOCK / "nano-banana-v6" / "nano-fixed-decals-v6.audit.json"
ENABLE_NANO_DECAL_EXPERIMENT = False
NANO_STYLE_ATLAS_V7 = ROOT / "public" / "textures" / "vaccine-fridge-nano-style-motifs-v7.png"
NANO_STYLE_AUDIT_V7 = LOCK / "nano-banana-v7" / "nano-style-motifs-v7.audit.json"
ENABLE_STYLE_FIT_V7 = False
ENABLE_PS1_DECAL_STYLE_V8 = False
# Identity-neutral fixed accents remain gated v2 assets until a generated
# replacement passes the same silhouette/alpha checks. Nano owns the material
# language; the locked authority still owns identifying graphics.
FIXED_STEEL_CORNER = ROOT / "public" / "textures" / "vaccine-fridge-gpt-steel-corner-v2.png"
FIXED_BOLT = ROOT / "public" / "textures" / "vaccine-fridge-gpt-bolt-v2.png"
ATLAS_SIZE = 128
MATERIAL_TILE_PX = 16.0
PANEL_TILE_PX = 32.0

SOURCE_RINGS = AUTHORITY["sourceRingsPx"]


def nano_palette(role: str, index: int) -> tuple[float, float, float, float]:
    audit = json.loads(NANO_AUDIT.read_text(encoding="utf-8"))
    entry = next(item for item in audit["materials"] if item["role"] == role)
    rgb = entry["paletteRgb"][index]
    return tuple(value / 255.0 for value in rgb) + (1.0,)


def source_atlas_placements() -> dict[str, tuple[int, int, int, int]]:
    """Return exact atlas rectangles generated by extract_fridge_source_atlas.py."""
    placements = {
        "front": (0, 0, 39, 96),
        "side": (40, 0, 37, 96),
        "back": (78, 0, 37, 96),
    }
    if not ATLAS.exists():
        raise FileNotFoundError(
            f"Missing {ATLAS}. Run tools/authoring/extract_fridge_source_atlas.py first."
        )
    return placements


def clear_scene() -> None:
    for obj in list(bpy.data.objects):
        bpy.data.objects.remove(obj, do_unlink=True)
    for mesh in list(bpy.data.meshes):
        bpy.data.meshes.remove(mesh)
    for material in list(bpy.data.materials):
        bpy.data.materials.remove(material)


def solid_material(name: str, rgba: tuple[float, float, float, float]):
    material = bpy.data.materials.new(name)
    material.diffuse_color = rgba
    material.use_nodes = True
    bsdf = material.node_tree.nodes.get("Principled BSDF")
    bsdf.inputs["Base Color"].default_value = rgba
    bsdf.inputs["Roughness"].default_value = 0.92
    bsdf.inputs["Alpha"].default_value = rgba[3]
    if rgba[3] < 1.0:
        material.surface_render_method = "DITHERED"
    return material


def source_material(image_path: Path = ATLAS):
    material = bpy.data.materials.new("source_pixels_locked")
    material.use_nodes = True
    material.use_backface_culling = True
    nodes = material.node_tree.nodes
    links = material.node_tree.links
    bsdf = nodes.get("Principled BSDF")
    image = bpy.data.images.load(str(image_path), check_existing=True)
    texture = nodes.new("ShaderNodeTexImage")
    texture.image = image
    texture.interpolation = "Closest"
    links.new(texture.outputs["Color"], bsdf.inputs["Base Color"])
    alpha_clip = nodes.new("ShaderNodeMath")
    alpha_clip.operation = "GREATER_THAN"
    alpha_clip.inputs[1].default_value = 0.5
    links.new(texture.outputs["Alpha"], alpha_clip.inputs[0])
    links.new(alpha_clip.outputs[0], bsdf.inputs["Alpha"])
    bsdf.inputs["Roughness"].default_value = 1.0
    return material


def image_surface_material(name: str, image_path: Path):
    material = bpy.data.materials.new(name)
    material.use_nodes = True
    material.use_backface_culling = True
    nodes = material.node_tree.nodes
    links = material.node_tree.links
    bsdf = nodes.get("Principled BSDF")
    texture = nodes.new("ShaderNodeTexImage")
    texture.image = bpy.data.images.load(str(image_path), check_existing=True)
    texture.interpolation = "Closest"
    links.new(texture.outputs["Color"], bsdf.inputs["Base Color"])
    bsdf.inputs["Roughness"].default_value = 1.0
    return material


def tiled_material(name: str, image_path: Path):
    """Unlit-neutral material field that repeats in model-pixel space."""
    material = image_surface_material(name, image_path)
    texture = next(node for node in material.node_tree.nodes if node.type == "TEX_IMAGE")
    texture.extension = "REPEAT"
    return material


def tiled_material_set(name: str, image_path: Path):
    """Front/side/top value steps sharing one Nano-authored motif layout."""
    suffix = f"-microtile-{NANO_VERSION}.png"
    stem = image_path.name.replace(suffix, "")
    side_path = image_path.with_name(f"{stem}-side{suffix}")
    top_path = image_path.with_name(f"{stem}-top{suffix}")
    return (
        tiled_material(f"{name}_front", image_path),
        tiled_material(f"{name}_side", side_path),
        tiled_material(f"{name}_top", top_path),
    )


def material_sequence(material):
    return material if isinstance(material, tuple) else (material,)


def image_decal_material(name: str, image_path: Path):
    material = bpy.data.materials.new(name)
    material.use_nodes = True
    material.use_backface_culling = True
    material.surface_render_method = "DITHERED"
    nodes = material.node_tree.nodes
    links = material.node_tree.links
    bsdf = nodes.get("Principled BSDF")
    texture = nodes.new("ShaderNodeTexImage")
    texture.image = bpy.data.images.load(str(image_path), check_existing=True)
    texture.interpolation = "Closest"
    links.new(texture.outputs["Color"], bsdf.inputs["Base Color"])
    links.new(texture.outputs["Color"], bsdf.inputs["Emission Color"])
    links.new(texture.outputs["Alpha"], bsdf.inputs["Alpha"])
    bsdf.inputs["Emission Strength"].default_value = 0.25
    bsdf.inputs["Roughness"].default_value = 1.0
    return material


def add_quad(name: str, material, points_px, uv_px, parent, extras=None):
    mesh = bpy.data.meshes.new(name + "_mesh")
    bm = bmesh.new()
    uv_layer = bm.loops.layers.uv.verify()
    verts = [bm.verts.new(tuple(value / PPU for value in point)) for point in points_px]
    face = bm.faces.new(verts)
    for loop, (u_px, v_top_px) in zip(face.loops, uv_px):
        loop[uv_layer].uv = (u_px / ATLAS_SIZE, 1.0 - (v_top_px / ATLAS_SIZE))
    bm.to_mesh(mesh)
    bm.free()
    obj = bpy.data.objects.new(name, mesh)
    bpy.context.scene.collection.objects.link(obj)
    obj.data.materials.append(material)
    obj.parent = parent
    if extras:
        for key, value in extras.items():
            obj[key] = value
    return obj


def add_image_quad(name: str, material, points_px, parent, extras=None, uv=None):
    mesh = bpy.data.meshes.new(name + "_mesh")
    bm = bmesh.new()
    uv_layer = bm.loops.layers.uv.verify()
    verts = [bm.verts.new(tuple(value / PPU for value in point)) for point in points_px]
    face = bm.faces.new(verts)
    coordinates = uv or ((0, 0), (1, 0), (1, 1), (0, 1))
    for loop, coordinate in zip(face.loops, coordinates):
        loop[uv_layer].uv = coordinate
    bm.to_mesh(mesh)
    bm.free()
    obj = bpy.data.objects.new(name, mesh)
    bpy.context.scene.collection.objects.link(obj)
    obj.data.materials.append(material)
    obj.parent = parent
    if extras:
        for key, value in extras.items():
            obj[key] = value
    return obj


def add_tiled_image_quad(name: str, material, points_px, uv_axes, parent, extras=None):
    """Map a 16px logical material field at exactly one texel per model pixel."""
    axis_index = {"x": 0, "y": 1, "z": 2}
    u_axis, v_axis = (axis_index[axis] for axis in uv_axes)
    mesh = bpy.data.meshes.new(name + "_mesh")
    bm = bmesh.new()
    uv_layer = bm.loops.layers.uv.verify()
    verts = [bm.verts.new(tuple(value / PPU for value in point)) for point in points_px]
    face = bm.faces.new(verts)
    for loop, point in zip(face.loops, points_px):
        loop[uv_layer].uv = (
            point[u_axis] / MATERIAL_TILE_PX,
            point[v_axis] / MATERIAL_TILE_PX,
        )
    bm.to_mesh(mesh)
    bm.free()
    obj = bpy.data.objects.new(name, mesh)
    bpy.context.scene.collection.objects.link(obj)
    obj.data.materials.append(material)
    obj.parent = parent
    if extras:
        for key, value in extras.items():
            obj[key] = value
    return obj


def add_box(name: str, bounds_px, material, parent, bevel_role: str):
    """Create an explicit six-face box through bmesh; no primitive operator."""
    x0, y0, z0, x1, y1, z1 = bounds_px
    coordinates = [
        (x0, y0, z0), (x1, y0, z0), (x1, y1, z0), (x0, y1, z0),
        (x0, y0, z1), (x1, y0, z1), (x1, y1, z1), (x0, y1, z1),
    ]
    indices = [
        (0, 3, 2, 1), (4, 5, 6, 7),
        (0, 1, 5, 4), (1, 2, 6, 5),
        (2, 3, 7, 6), (3, 0, 4, 7),
    ]
    mesh = bpy.data.meshes.new(name + "_mesh")
    bm = bmesh.new()
    uv_layer = bm.loops.layers.uv.verify()
    verts = [bm.verts.new(tuple(value / PPU for value in point)) for point in coordinates]
    for face_indices in indices:
        face = bm.faces.new([verts[index] for index in face_indices])
        face_points = [coordinates[index] for index in face_indices]
        spans = [max(point[axis] for point in face_points) - min(point[axis] for point in face_points)
                 for axis in range(3)]
        normal_axis = spans.index(min(spans))
        if isinstance(material, tuple):
            center = [sum(point[axis] for point in face_points) / len(face_points)
                      for axis in range(3)]
            if normal_axis == 2:
                face.material_index = 2 if center[2] > (z0 + z1) / 2 else 1
            elif normal_axis == 0:
                face.material_index = 1
            else:
                face.material_index = 0 if center[1] <= (y0 + y1) / 2 else 1
        u_axis, v_axis = ((1, 2) if normal_axis == 0 else
                          (0, 2) if normal_axis == 1 else (0, 1))
        for loop, point in zip(face.loops, face_points):
            loop[uv_layer].uv = (point[u_axis] / MATERIAL_TILE_PX,
                                 point[v_axis] / MATERIAL_TILE_PX)
    bm.to_mesh(mesh)
    bm.free()
    obj = bpy.data.objects.new(name, mesh)
    bpy.context.scene.collection.objects.link(obj)
    for item in material_sequence(material):
        obj.data.materials.append(item)
    obj.parent = parent
    obj["sourceGeometryRole"] = bevel_role
    return obj


def add_loft(name: str, rings, material, parent):
    """Create the structural hull from explicit width/depth/z source rings."""
    mesh = bpy.data.meshes.new(name + "_mesh")
    bm = bmesh.new()
    uv_layer = bm.loops.layers.uv.verify()

    def add_face(vertices):
        face = bm.faces.new(vertices)
        points = [[coordinate * PPU for coordinate in loop.vert.co] for loop in face.loops]
        spans = [max(point[axis] for point in points) - min(point[axis] for point in points)
                 for axis in range(3)]
        normal_axis = spans.index(min(spans))
        if isinstance(material, tuple):
            center = [sum(point[axis] for point in points) / len(points)
                      for axis in range(3)]
            if normal_axis == 2:
                face.material_index = 2
            elif normal_axis == 0:
                face.material_index = 1
            else:
                face.material_index = 0 if center[1] < 0 else 1
        u_axis, v_axis = ((1, 2) if normal_axis == 0 else
                          (0, 2) if normal_axis == 1 else (0, 1))
        for loop, point in zip(face.loops, points):
            loop[uv_layer].uv = (point[u_axis] / MATERIAL_TILE_PX,
                                 point[v_axis] / MATERIAL_TILE_PX)
        return face
    ring_verts = []
    for ring in rings:
        z, width, front_y, back_y = ring
        x = width / 2.0
        ring_verts.append([
            bm.verts.new((-x / PPU, front_y / PPU, z / PPU)),
            bm.verts.new(( x / PPU, front_y / PPU, z / PPU)),
            bm.verts.new(( x / PPU, back_y / PPU, z / PPU)),
            bm.verts.new((-x / PPU, back_y / PPU, z / PPU)),
        ])
    add_face(list(reversed(ring_verts[0])))
    add_face(ring_verts[-1])
    for segment_index, (lower, upper) in enumerate(zip(ring_verts, ring_verts[1:])):
        for index in range(4):
            lower_z = rings[segment_index][0]
            upper_z = rings[segment_index + 1][0]
            if index == 0 and lower_z >= 20.6 and upper_z <= 86.45:
                continue
            add_face((lower[index], lower[(index + 1) % 4], upper[(index + 1) % 4], upper[index]))
    bm.to_mesh(mesh)
    bm.free()
    obj = bpy.data.objects.new(name, mesh)
    bpy.context.scene.collection.objects.link(obj)
    for item in material_sequence(material):
        obj.data.materials.append(item)
    obj.parent = parent
    obj["sourceGeometryRole"] = "structural_hull"
    return obj


def add_conformal_source_skins(rings, material, parent):
    """Bind source pixels to the measured front/right/back hull surfaces."""
    def finish(name, bm):
        mesh = bpy.data.meshes.new(name + "_mesh")
        bm.to_mesh(mesh)
        bm.free()
        obj = bpy.data.objects.new(name, mesh)
        bpy.context.scene.collection.objects.link(obj)
        obj.data.materials.append(material)
        obj.parent = parent
        obj["texturePolicy"] = "geometry_bound_source_pixels"
        return obj

    # Front: each row uses the matching visible atlas interval rather than
    # stretching all 39 atlas pixels into a narrower crown row.
    bm = bmesh.new(); uv_layer = bm.loops.layers.uv.verify()
    front_rows = []
    for z, width, front_y, _ in rings:
        half = width / 2
        u0, u1 = 19.5 - half, 19.5 + half
        front_rows.append((
            bm.verts.new((-half / PPU, (front_y - .60) / PPU, z / PPU)),
            bm.verts.new(( half / PPU, (front_y - .60) / PPU, z / PPU)),
            u0, u1, 96 - z,
        ))
    for lower, upper in zip(front_rows, front_rows[1:]):
        face = bm.faces.new((lower[0], lower[1], upper[1], upper[0]))
        for loop, uv_px in zip(face.loops, ((lower[2],lower[4]),(lower[3],lower[4]),(upper[3],upper[4]),(upper[2],upper[4]))):
            loop[uv_layer].uv = (uv_px[0]/ATLAS_SIZE, 1-uv_px[1]/ATLAS_SIZE)
    finish("source_skin_front", bm)

    # Right side: vertices follow both the depth taper and the width profile.
    bm = bmesh.new(); uv_layer = bm.loops.layers.uv.verify(); side_rows=[]
    for z, width, front_y, back_y in rings:
        x = width / 2 + .08
        side_rows.append((
            bm.verts.new((x/PPU, (front_y+2.2)/PPU, z/PPU)),
            bm.verts.new((x/PPU, back_y/PPU, z/PPU)), 96-z,
        ))
    for lower, upper in zip(side_rows, side_rows[1:]):
        face = bm.faces.new((lower[0], lower[1], upper[1], upper[0]))
        for loop, uv_px in zip(face.loops, ((74,lower[2]),(40,lower[2]),(40,upper[2]),(74,upper[2]))):
            loop[uv_layer].uv = (uv_px[0]/ATLAS_SIZE, 1-uv_px[1]/ATLAS_SIZE)
    finish("source_skin_side_right", bm)

    # Back follows the same profile instead of remaining a floating rectangle.
    bm = bmesh.new(); uv_layer = bm.loops.layers.uv.verify(); back_rows=[]
    for z, width, _, back_y in rings:
        half = width / 2
        back_rows.append((
            bm.verts.new(( half/PPU, (back_y+.08)/PPU, z/PPU)),
            bm.verts.new((-half/PPU, (back_y+.08)/PPU, z/PPU)), 96-z,
        ))
    for lower, upper in zip(back_rows, back_rows[1:]):
        face = bm.faces.new((lower[0], lower[1], upper[1], upper[0]))
        for loop, uv_px in zip(face.loops, ((78,lower[2]),(115,lower[2]),(115,upper[2]),(78,upper[2]))):
            loop[uv_layer].uv = (uv_px[0]/ATLAS_SIZE, 1-uv_px[1]/ATLAS_SIZE)
    finish("source_skin_back", bm)


def add_conformal_side_panel(rings, material, parent):
    """Tile the clean steel field only over the real side-panel vertical band."""
    panel_rings = [ring for ring in rings if 20.6 <= ring[0] <= 86.45]
    bm = bmesh.new()
    uv_layer = bm.loops.layers.uv.verify()
    rows = []
    for z, width, front_y, back_y in panel_rings:
        x = width / 2 + .08
        rows.append((
            bm.verts.new((x/PPU, (front_y+2.2)/PPU, z/PPU)),
            bm.verts.new((x/PPU, back_y/PPU, z/PPU)), z, front_y+2.2, back_y,
        ))
    for lower, upper in zip(rows, rows[1:]):
        face = bm.faces.new((lower[0], lower[1], upper[1], upper[0]))
        for loop, uv_px in zip(face.loops, (
            (lower[3], lower[2]), (lower[4], lower[2]),
            (upper[4], upper[2]), (upper[3], upper[2]),
        )):
            loop[uv_layer].uv = (uv_px[0]/PANEL_TILE_PX, uv_px[1]/PANEL_TILE_PX)
    mesh = bpy.data.meshes.new("nano_tile_side_panel_mesh")
    bm.to_mesh(mesh)
    bm.free()
    obj = bpy.data.objects.new("nano_tile_side_panel", mesh)
    bpy.context.scene.collection.objects.link(obj)
    obj.data.materials.append(material)
    obj.parent = parent
    obj["texturePolicy"] = "TILE_WORLD_SCALE"
    return obj


def add_conformal_back_panel(rings, material, parent):
    """Tile the clean steel field over the main back panel, never crown/base."""
    panel_rings = [ring for ring in rings if 20.6 <= ring[0] <= 86.45]
    bm = bmesh.new()
    uv_layer = bm.loops.layers.uv.verify()
    rows = []
    for z, width, _, back_y in panel_rings:
        half = width / 2.0
        rows.append((
            bm.verts.new((half/PPU, (back_y+.08)/PPU, z/PPU)),
            bm.verts.new((-half/PPU, (back_y+.08)/PPU, z/PPU)),
            z, half,
        ))
    for lower, upper in zip(rows, rows[1:]):
        face = bm.faces.new((lower[0], lower[1], upper[1], upper[0]))
        for loop, uv_px in zip(face.loops, (
            (lower[3], lower[2]), (-lower[3], lower[2]),
            (-upper[3], upper[2]), (upper[3], upper[2]),
        )):
            loop[uv_layer].uv = (uv_px[0]/PANEL_TILE_PX, uv_px[1]/PANEL_TILE_PX)
    mesh = bpy.data.meshes.new("nano_tile_back_panel_mesh")
    bm.to_mesh(mesh)
    bm.free()
    obj = bpy.data.objects.new("nano_tile_back_panel", mesh)
    bpy.context.scene.collection.objects.link(obj)
    obj.data.materials.append(material)
    obj.parent = parent
    obj["texturePolicy"] = "TILE_WORLD_SCALE"
    return obj


def add_panel_detail_decals(rings, parent):
    """Reference-derived, fixed-size panel marks over a quiet scalable center."""
    main_rings = [ring for ring in rings if 20.6 <= ring[0] <= 86.45]
    body_half = max(ring[1] for ring in main_rings) / 2.0
    front_y = min(ring[2] for ring in main_rings) + 3.0
    back_y = max(ring[3] for ring in main_rings)
    side_x = body_half + 0.16
    steel_dark = solid_material("reference_panel_mark_dark", nano_palette("steel", 1))
    steel_light = solid_material("reference_panel_mark_light", nano_palette("steel", 2))

    def side_quad(name, material, y0, y1, z0, z1, uv=None):
        add_image_quad(
            name, material,
            [[side_x, y0, z0], [side_x, y1, z0],
             [side_x, y1, z1], [side_x, y0, z1]],
            parent, {"texturePolicy": "FIXED_DECAL", "generatedSource": "reference-style-profile-v1"}, uv=uv,
        )

    # One protected seam spans only the safe center; all other accents keep
    # their literal model-pixel size and follow side/back sockets.
    add_image_quad(
        "side_panel_semantic_seam_dark", steel_dark,
        [[side_x, front_y, 50.75], [side_x, back_y, 50.75],
         [side_x, back_y, 51.75], [side_x, front_y, 51.75]],
        parent, {"texturePolicy": "NINE_SLICE_SPAN"},
    )
    add_image_quad(
        "side_panel_semantic_seam_light", steel_light,
        [[side_x, front_y, 51.75], [side_x, back_y, 51.75],
         [side_x, back_y, 52.75], [side_x, front_y, 52.75]],
        parent, {"texturePolicy": "NINE_SLICE_SPAN"},
    )
    # Short 1px-thick rectangular marks reproduce the primary reference's
    # panel language.  They stay literal size and remain anchored to the back
    # edge when the cabinet width changes.
    for index, (material, y0, y1, z0, z1) in enumerate((
        (steel_dark, back_y - 8, back_y - 2, 66, 67),
        (steel_dark, back_y - 10, back_y - 4, 63, 64),
        (steel_light, back_y - 7, back_y - 2, 62, 63),
        (steel_dark, back_y - 9, back_y - 2, 31, 32),
        (steel_dark, back_y - 11, back_y - 4, 28, 29),
        (steel_light, back_y - 6, back_y - 2, 27, 28),
    )):
        side_quad(f"side_reference_panel_mark_{index}", material, y0, y1, z0, z1)

    # The reference does not scatter bolts over broad faces; the back therefore
    # keeps a calm repeating center and the one protected panel seam only.


def add_front_style_details(centers, shelf_elevations, parent):
    """Nano-derived semantic pixels: fixed bands, corners, and shelf lips."""
    teal_dark = solid_material("nano_teal_trim_dark", nano_palette("teal", 1))
    teal_light = solid_material("nano_teal_trim_light", nano_palette("teal", 2))
    cream_dark = solid_material("nano_cream_fastener", nano_palette("cream", 1))
    steel_dark = solid_material("nano_shelf_lip_dark", nano_palette("steel", 1))
    steel_light = solid_material("nano_shelf_lip_light", nano_palette("steel", 2))
    front_y = -15.90

    for bay_index, center in enumerate(centers):
        # One-pixel paired door bands reproduce the reference style's bright
        # top/left and dark bottom/right treatment without baking lighting.
        strips = (
            ("left_light", teal_light, center - 15, center - 14, 22, 82),
            ("top_light", teal_light, center - 15, center + 15, 81, 82),
            ("right_dark", teal_dark, center + 14, center + 15, 22, 82),
            ("bottom_dark", teal_dark, center - 15, center + 15, 22, 23),
        )
        for label, material, x0, x1, z0, z1 in strips:
            add_image_quad(
                f"door_trim_{label}_bay{bay_index}", material,
                [[x0, front_y, z0], [x1, front_y, z0],
                 [x1, front_y, z1], [x0, front_y, z1]],
                parent, {"texturePolicy": "FIXED_EDGE_REPEAT_COMPLETE_BAY",
                         "generatedSource": "nano-banana-style-contract"},
            )

        # Two short corner notches replace the previous scattered fasteners.
        # This is the same quiet-center / marked-corner grammar as inspo-2.
        for detail_index, (x0, x1, z0, z1) in enumerate((
            (center - 17.0, center - 14.0, 79.0, 80.0),
            (center + 14.0, center + 17.0, 24.0, 25.0),
        )):
            add_image_quad(
                f"cream_fixed_corner_notch_bay{bay_index}_{detail_index}", cream_dark,
                [[x0, front_y - .01, z0], [x1, front_y - .01, z0],
                 [x1, front_y - .01, z1], [x0, front_y - .01, z1]],
                parent, {"texturePolicy": "FIXED_CORNER_DECAL",
                         "generatedSource": "reference-style-profile-v1"},
            )

        for shelf_z in shelf_elevations:
            for label, material, z0, z1 in (
                ("dark", steel_dark, shelf_z, shelf_z + .5),
                ("light", steel_light, shelf_z + 1.15, shelf_z + 1.65),
            ):
                add_image_quad(
                    f"shelf_lip_{label}_bay{bay_index}_{shelf_z}", material,
                    [[center - 11.5, -15.86, z0], [center + 11.5, -15.86, z0],
                     [center + 11.5, -15.86, z1], [center - 11.5, -15.86, z1]],
                    parent, {"texturePolicy": "FIXED_EDGE_REPEAT_COMPLETE_BAY",
                             "generatedSource": "nano-banana-style-contract"},
                )


def add_top_style_details(parent, half_width=15.7):
    """Reference roof inset: fixed side caps and a width-adaptive center span."""
    cream_dark = solid_material("reference_roof_inset_dark", nano_palette("cream", 1))
    cream_light = solid_material("reference_roof_inset_light", nano_palette("cream", 2))
    z = 96.05
    left, right = -half_width + 3.7, half_width - 3.7
    details = (
        ("left_light", cream_light, (left, left + 2.0, -9.0, 10.0)),
        ("back_light", cream_light, (left, right, 8.0, 10.0)),
        ("right_dark", cream_dark, (right - 2.0, right, -9.0, 10.0)),
        ("front_dark", cream_dark, (left, right, -9.0, -7.0)),
    )
    for label, material, (x0, x1, y0, y1) in details:
        add_image_quad(
            f"roof_inset_{label}", material,
            [[x0, y0, z], [x1, y0, z], [x1, y1, z], [x0, y1, z]],
            parent, {"texturePolicy": "FIXED_INSET_EDGE",
                     "generatedSource": "reference-style-profile-v1"},
        )


def add_nano_margin_decals(rings, shelf_elevations, parent):
    """Fixed-size Nano motifs; each UV island includes protected empty margins."""
    audit = json.loads(NANO_DECAL_AUDIT.read_text(encoding="utf-8"))
    atlas_width, atlas_height = audit["atlasSizePx"]
    regions = {item["name"]: item["atlasRectPx"] for item in audit["decals"]}
    decal_material = image_decal_material("nano_margin_decals_v6", NANO_DECAL_ATLAS)

    def uv_for(name):
        x, y, width, height = regions[name]
        u0, u1 = x / atlas_width, (x + width) / atlas_width
        v0, v1 = 1 - (y + height) / atlas_height, 1 - y / atlas_height
        return ((u0, v0), (u1, v0), (u1, v1), (u0, v1))

    def front(name, decal, x0, x1, z0, z1, y=-15.94):
        add_image_quad(
            name, decal_material,
            [[x0,y,z0],[x1,y,z0],[x1,y,z1],[x0,y,z1]], parent,
            {"texturePolicy": "FIXED_DECAL_WITH_MARGIN",
             "generatedSource": "nano-banana-v6", "protectedAtlasMarginPx": 4},
            uv=uv_for(decal),
        )

    front("nano_cream_corner_chip", "cream_corner_chip", -18, -12, 78, 84)
    front("nano_teal_upper_chip", "teal_chip", -15, -11, 70, 74)
    front("nano_teal_lower_corner", "teal_corner", 9, 15, 23, 29)
    front("nano_glass_stair", "glass_stair", -11.5, -6.5, 66, 74, -15.965)
    front("nano_crown_fastener", "steel_fastener", 13, 17, 87.8, 91.8, -15.82)
    for index, shelf_z in enumerate(shelf_elevations):
        front(f"nano_shelf_end_{index}", "shelf_end", 7.5, 13.5,
              shelf_z - .5, shelf_z + 2.5, -15.875)

    main_rings = [ring for ring in rings if 20.6 <= ring[0] <= 86.45]
    body_half = max(ring[1] for ring in main_rings) / 2.0
    back_y = max(ring[3] for ring in main_rings)
    side_x = body_half + .18

    def side(name, decal, y0, y1, z0, z1):
        add_image_quad(
            name, decal_material,
            [[side_x,y0,z0],[side_x,y1,z0],[side_x,y1,z1],[side_x,y0,z1]], parent,
            {"texturePolicy": "FIXED_DECAL_WITH_MARGIN",
             "generatedSource": "nano-banana-v6", "protectedAtlasMarginPx": 4},
            uv=uv_for(decal),
        )

    side("nano_side_dark_mark", "steel_dark_mark", back_y-10, back_y-4, 64, 67)
    side("nano_side_light_mark", "steel_light_mark", back_y-9, back_y-3, 29, 32)


def add_style_fit_geometry_v7(parent):
    """Reference-fit relief: compact construction details, never texture-faked depth."""
    steel_dark = solid_material("v7_service_slot_dark", nano_palette("steel", 1))
    teal_dark = solid_material("v7_service_slot_recess", nano_palette("teal", 1))
    steel_light = solid_material("v7_crown_catch_light", nano_palette("steel", 2))

    # Three compact hinge plates break the long door edge without recreating
    # the incorrect continuous vertical bar seen in earlier iterations.
    for index, z0 in enumerate((27.0, 50.0, 75.0)):
        add_box(
            f"v7_door_hinge_{index}",
            [15.0, -16.25, z0, 16.9, -15.35, z0 + 2.5],
            steel_dark,
            parent,
            "fixed_hinge_hardware",
        )

    # Repeating lower-side service slots are actual shallow boxes. One measured
    # template and a loop preserve their construction rhythm at every variant.
    for index in range(3):
        z0 = 27.0 + index * 3.0
        add_box(
            f"v7_side_service_slot_{index}",
            [18.92, 7.5, z0, 19.42, 13.5, z0 + 0.85],
            teal_dark,
            parent,
            "loop_generated_service_slot",
        )

    # Two small raised catches reinforce the stepped crown silhouette.
    for label, x0, x1 in (("left", -17.8, -15.3), ("right", 15.3, 17.8)):
        add_box(
            f"v7_crown_corner_catch_{label}",
            [x0, -15.9, 87.8, x1, -15.15, 89.5],
            steel_light,
            parent,
            "fixed_crown_corner_hardware",
        )


def add_nano_style_motifs_v7(rings, shelf_elevations, parent):
    """Larger Nano-authored clusters with fixed model-pixel size and safe gutters."""
    audit = json.loads(NANO_STYLE_AUDIT_V7.read_text(encoding="utf-8"))
    atlas_width, atlas_height = audit["atlasSizePx"]
    regions = {item["name"]: item["atlasRectPx"] for item in audit["decals"]}
    material = image_decal_material("nano_style_motifs_v7", NANO_STYLE_ATLAS_V7)

    def uv_for(name):
        x, y, width, height = regions[name]
        return (
            (x / atlas_width, 1 - (y + height) / atlas_height),
            ((x + width) / atlas_width, 1 - (y + height) / atlas_height),
            ((x + width) / atlas_width, 1 - y / atlas_height),
            (x / atlas_width, 1 - y / atlas_height),
        )

    extras = {
        "texturePolicy": "FIXED_SOCKET_DECAL_WITH_MARGIN",
        "generatedSource": "nano-banana-v7-all-five-style-authorities",
        "protectedAtlasMarginPx": 4,
        "internalTransparentMarginPx": 3,
        "scalePolicy": "translate_anchor_keep_literal_model_pixels",
    }

    def front(name, motif, x0, x1, z0, z1, y=-16.52):
        add_image_quad(
            name, material,
            [[x0, y, z0], [x1, y, z0], [x1, y, z1], [x0, y, z1]],
            parent, extras, uv=uv_for(motif),
        )

    front("v7_cream_upper_corner", "cream_top_left", -18.2, -10.2, 78.0, 86.0)
    front("v7_cream_lower_corner", "cream_bottom_right", 9.2, 17.2, 20.5, 28.5)
    front("v7_teal_upper_stair", "teal_top_left", -15.2, -7.2, 69.0, 78.0, -16.56)
    front("v7_teal_lower_corner", "teal_bottom_right", 7.0, 15.0, 22.2, 30.2, -16.56)
    front("v7_glass_stair_glint", "glass_glint", -9.0, -3.0, 65.0, 75.0, -16.59)
    front("v7_grille_corner", "grille_corner", -13.0, -5.0, 5.0, 13.0, -16.58)
    front("v7_handle_cap", "handle_cap", -19.2, -11.2, 42.0, 48.0, -19.25)

    for index, shelf_z in enumerate(shelf_elevations):
        front(
            f"v7_shelf_end_{index}", "shelf_end",
            6.0, 14.0, shelf_z - 1.0, shelf_z + 5.0, -16.60,
        )

    main_rings = [ring for ring in rings if 20.6 <= ring[0] <= 86.45]
    side_x = max(ring[1] for ring in main_rings) / 2.0 + .24
    back_y = max(ring[3] for ring in main_rings)

    def side(name, motif, y0, y1, z0, z1):
        add_image_quad(
            name, material,
            [[side_x, y0, z0], [side_x, y1, z0],
             [side_x, y1, z1], [side_x, y0, z1]],
            parent, extras, uv=uv_for(motif),
        )

    side("v7_side_upper_corner", "steel_top_left", back_y - 10, back_y - 2, 74, 82)
    side("v7_side_lower_corner", "steel_bottom_right", back_y - 10, back_y - 2, 38, 46)
    side("v7_side_double_seam", "steel_double_seam", back_y - 12, back_y - 3, 59, 63)


def add_ps1_decal_details_v8(rings, shelf_elevations, parent):
    """PS1-style detail split: macro form is mesh; every small fitting is a decal."""
    add_nano_style_motifs_v7(rings, shelf_elevations, parent)

    audit = json.loads(NANO_STYLE_AUDIT_V7.read_text(encoding="utf-8"))
    atlas_width, atlas_height = audit["atlasSizePx"]
    regions = {item["name"]: item["atlasRectPx"] for item in audit["decals"]}
    material = image_decal_material("nano_ps1_fittings_v8", NANO_STYLE_ATLAS_V7)

    def uv_for(name):
        x, y, width, height = regions[name]
        return (
            (x / atlas_width, 1 - (y + height) / atlas_height),
            ((x + width) / atlas_width, 1 - (y + height) / atlas_height),
            ((x + width) / atlas_width, 1 - y / atlas_height),
            (x / atlas_width, 1 - y / atlas_height),
        )

    extras = {
        "texturePolicy": "PS1_FIXED_DETAIL_DECAL",
        "generatedSource": "nano-banana-v7-all-five-style-authorities",
        "protectedAtlasMarginPx": 4,
        "internalTransparentMarginPx": 3,
        "geometryDetailThresholdPx": 4,
        "scalePolicy": "anchor_translate_only_never_scale_fitting",
    }

    def front(name, motif, x0, x1, z0, z1, y=-16.63):
        add_image_quad(
            name, material,
            [[x0, y, z0], [x1, y, z0], [x1, y, z1], [x0, y, z1]],
            parent, extras, uv=uv_for(motif),
        )

    # Hinge plates and crown catches are deliberately flat pixels, not boxes.
    for index, z0 in enumerate((27.0, 50.0, 75.0)):
        front(f"v8_decal_hinge_{index}", "steel_bottom_right", 14.2, 17.2, z0, z0 + 3.0)
    front("v8_decal_crown_catch_left", "steel_top_left", -18.0, -13.0, 86.8, 91.8)
    front("v8_decal_crown_catch_right", "steel_bottom_right", 13.0, 18.0, 86.8, 91.8)

    main_rings = [ring for ring in rings if 20.6 <= ring[0] <= 86.45]
    side_x = max(ring[1] for ring in main_rings) / 2.0 + .28
    back_y = max(ring[3] for ring in main_rings)
    add_image_quad(
        "v8_decal_side_service_dashes", material,
        [[side_x, back_y - 13, 27], [side_x, back_y - 3, 27],
         [side_x, back_y - 3, 30], [side_x, back_y - 13, 30]],
        parent, extras, uv=uv_for("side_service_dashes"),
    )


def build(out_path: Path = OUT, root_name: str = "vaccine_fridge_source_true_root",
          root_extras: dict | None = None):
    placements = source_atlas_placements()
    clear_scene()
    root = bpy.data.objects.new(root_name, None)
    bpy.context.scene.collection.objects.link(root)
    root["pixelsPerUnit"] = AUTHORITY["pixelsPerUnit"]
    root["authoritySha256"] = AUTHORITY["authoritySha256"]
    root["sourceTruthVersion"] = AUTHORITY["schemaVersion"]
    root["adaptivePolicy"] = AUTHORITY["adaptive"]["policy"]
    root["doorBayWidthPx"] = AUTHORITY["adaptive"]["doorBayWidthPx"]
    if root_extras:
        for key, value in root_extras.items():
            root[key] = value

    materials = {
        key: solid_material(f"structure_{key}", tuple(rgba))
        for key, rgba in AUTHORITY["materials"].items()
    }
    cream_tile = tiled_material_set("nano_cream_microfield", NANO_CREAM_TILE)
    steel_tile = tiled_material_set("nano_steel_microfield", NANO_STEEL_TILE)
    steel_panel_tile = tiled_material("nano_steel_panel_microfield", NANO_STEEL_PANEL_TILE)
    teal_tile = tiled_material_set("nano_teal_microfield", NANO_TEAL_TILE)
    materials.update({"cream": cream_tile, "steel": steel_tile, "teal": teal_tile})
    reflection = image_decal_material("source_glass_reflection", GLASS_OVERLAY)
    display_pixels = image_surface_material("source_display_pixels", DISPLAY_TEXTURE)
    grille_pixels = image_surface_material("source_grille_pixels", GRILLE_TEXTURE)

    # Explicit profile rings measured from the locked front and side silhouettes.
    add_loft("source_hull", SOURCE_RINGS, materials["steel"], root)

    # Unique structural parts are assembled from the canonical grid spec.
    # Generated correction sheets remain advisory until their measurements are
    # accepted into that spec, so image-model drift cannot silently alter a GLB.
    for part in AUTHORITY["parts"]:
        add_box(part["name"], part["boundsPx"], materials[part["material"]], root, part["role"])

    # Repeated parts use one measured template rather than independent copies.
    shelf_spec = AUTHORITY["shelfTemplate"]
    for shelf_z in shelf_spec["elevationsPx"]:
        body = list(shelf_spec["bodyBoundsPx"])
        lip = list(shelf_spec["lipBoundsPx"])
        body[2] += shelf_z
        body[5] += shelf_z
        lip[2] += shelf_z
        lip[5] += shelf_z
        add_box(f"shelf_{shelf_z}", body, materials[shelf_spec["bodyMaterial"]], root, "shelf")
        add_box(f"shelf_lip_{shelf_z}", lip, materials[shelf_spec["lipMaterial"]], root, "shelf_front_lip")

    image_materials = {
        "glassReflection": reflection,
    }
    for surface in AUTHORITY["imageSurfaces"]:
        if surface["name"] == "source_top_surface":
            add_tiled_image_quad(
                "nano_tile_top_surface", cream_tile[2], surface["pointsPx"], ("x", "y"), root,
                {"texturePolicy": "TILE_WORLD_SCALE_16PX", "generatedSource": "nano-banana-2"},
            )
            continue
        add_image_quad(surface["name"], image_materials[surface["texture"]],
                       surface["pointsPx"], root,
                       {"texturePolicy": surface["texturePolicy"]})

    # Structural surfaces use clean generated material fields. Full-view source
    # skins are intentionally absent: their baked frame, crown, seam and shadow
    # pixels would duplicate geometry and create the small edge errors this
    # pipeline is designed to reject.
    add_conformal_side_panel(SOURCE_RINGS, steel_panel_tile, root)
    add_conformal_back_panel(SOURCE_RINGS, steel_panel_tile, root)
    add_panel_detail_decals(SOURCE_RINGS, root)
    add_front_style_details([0.0], shelf_spec["elevationsPx"], root)
    add_top_style_details(root)
    if ENABLE_NANO_DECAL_EXPERIMENT:
        add_nano_margin_decals(SOURCE_RINGS, shelf_spec["elevationsPx"], root)
    if ENABLE_STYLE_FIT_V7:
        add_style_fit_geometry_v7(root)
        add_nano_style_motifs_v7(SOURCE_RINGS, shelf_spec["elevationsPx"], root)
    if ENABLE_PS1_DECAL_STYLE_V8:
        add_ps1_decal_details_v8(SOURCE_RINGS, shelf_spec["elevationsPx"], root)

    x0, x1, z0, z1 = AUTHORITY["frontFeaturesPx"]["display"]
    add_image_quad("fixed_display", display_pixels,
                   [(x0,-16.02,z0),(x1,-16.02,z0),(x1,-16.02,z1),(x0,-16.02,z1)], root,
                   {"texturePolicy":"FIXED_CENTER_1TO1"})
    x0, x1, z0, z1 = AUTHORITY["frontFeaturesPx"]["grille"]
    add_image_quad("fixed_grille", grille_pixels,
                   [(x0,-15.68,z0),(x1,-15.68,z0),(x1,-15.68,z1),(x0,-15.68,z1)], root,
                   {"texturePolicy":"FIXED_PER_BAY_1TO1"})

    for name, position in AUTHORITY["socketsPx"].items():
        socket = bpy.data.objects.new(name, None)
        bpy.context.scene.collection.objects.link(socket)
        socket.parent = root
        socket.location = tuple(value / PPU for value in position)
        socket["restPositionPx"] = list(position)
        socket["adaptivePolicy"] = "translate_only_keep_scale_1"

    out_path.parent.mkdir(parents=True, exist_ok=True)
    for obj in bpy.context.scene.objects:
        obj.select_set(True)
    bpy.context.view_layer.objects.active = root
    bpy.ops.export_scene.gltf(
        filepath=str(out_path), export_format="GLB", use_selection=True,
        export_yup=True, export_materials="EXPORT", export_extras=True,
    )
    # Blender's Closest sampler exports NEAREST_MIPMAP_NEAREST.  Source pixels
    # must not acquire generated mip levels in Three.js, so patch the same-size
    # JSON token to plain NEAREST without disturbing GLB chunk offsets.
    glb_bytes = out_path.read_bytes()
    glb_bytes = glb_bytes.replace(b'"minFilter":9984', b'"minFilter":9728')
    out_path.write_bytes(glb_bytes)
    print(json.dumps({
        "model": str(out_path),
        "materialTiles": [str(NANO_CREAM_TILE), str(NANO_STEEL_TILE)],
        "sourceSha256": AUTHORITY["authoritySha256"],
        "schemaVersion": AUTHORITY["schemaVersion"],
        "dimensionsPx": [39, 37, 96],
    }, indent=2))


if __name__ == "__main__":
    build()
