#!/usr/bin/env python3
"""Audit every resize and texture adaptation ONE AT A TIME, against glm-5.3.

    python3 tools/authoring/resize_audit.py work/ps1 --asset "jukebox"
    python3 tools/authoring/resize_audit.py work/ps1 --report

Authoring tool. NOT a build, CI or runtime dependency.

WHY THIS IS NOT THE JUDGE LOOP. `make_prop`'s judges are shown the whole prop at
three sizes and asked what is wrong with it. That is the right question for
"does this read as the object", and it is the wrong question for "was THIS
decision correct" -- and the repo has the numbers on what that costs. Both
language judges scored a cabinet carrying five stacked ARCADE marquees at two
blocking faults, exactly what they gave the corrected cabinet beside it, and
passed a pinball standing on stilts at zero. 181 of 306 blocking faults across
three runs were one sentence in different words. A grader looking at an entire
machine is answering about the machine.

So this asks about ONE ADAPTATION, with only that adaptation in front of it, and
it says what the tool did and why before asking whether it was right. A model
that is told "the tool repeated rows 442..479 eight times because the model
named that place and it measured bare" can check that claim against the picture.
A model shown a whole taller vending machine cannot.

WHAT COUNTS AS AN ADAPTATION. A part held at its drawn size did not adapt and is
not audited -- auditing it would be asking about the reference, not about this
tool. What adapts is:

    SPAN      a part whose rule is not `fixed` on one or both axes
    COUNT     a part that comes per bay or per tier, so a bigger prop has more
    BOUGHT    a part whose widened artwork was generated by wide_art
    BODY      the growth bands the carcass itself grows on, or the stretch it
              falls back to when it has nowhere bare

Typically five to fifteen per prop, not fifty, so the audit costs about what one
judge round costs -- glm-5.3-flash is $0.0002 a call, measured in this repo.

AND EVERY VERDICT HAS A LEVER. CLAUDE.md's rule: anything that can block must be
able to correct. A FAIL comes back naming the part and the rule it should have
had, which is exactly the judge loop's patch schema, so a failed audit is a
patch and not a complaint. An audit with no correcting channel would be the
fault this repo has recorded four times.
"""
import argparse
import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "tools" / "authoring"))

PASS, FAIL, UNSURE = "PASS", "FAIL", "UNSURE"

# The rules a patch may name, quoted from make_prop so a verdict cannot ask for
# something the loop has no field to express.
RESIZES = ("fixed", "spanx_center", "spanx_repeat", "spany_center",
           "spany_repeat")

PROMPT = """You are auditing ONE resizing decision made by a tool that turns a
drawn reference into a resizable 3-D prop. Answer about this decision only.

THE PROP is a {asset}.
THE PART is "{part}".

WHAT THE TOOL DID, and why:

{did}

THE PICTURES, in order:
  1. the part as it is drawn in the reference elevation
  2. the prop at its drawn size, framed on this part
  3. the prop at {scale}, framed on the same part

Image 3 is the decision. Image 2 is the same decision at a size where it cannot
be wrong, and image 1 is what the part is supposed to be.

JUDGE ONE THING: at the larger size, is this part still the thing image 1 shows?

AND SAY WHICH THING IS WRONG. The part is drawn ON the body, and the body
carries its own artwork around it -- panel, labels, trim, seams. If what is
stretched or repeated is the BODY behind and around the part rather than the
part itself, that is a fault of the body and not of this decision. Both are
worth reporting; they are fixed in different places, so do not confuse them.

It has FAILED if any of these is true:
  - the artwork is stretched or squashed: letters, faces, mouldings or motifs
    with proportions image 1 does not have
  - something that appears ONCE in image 1 appears more than once in image 3
  - a seam, a smear, a repeated band or a blank patch a player could point at
  - the part has come away from what it is mounted on, or floats
  - it has gained material that is not what the reference draws there

It has PASSED if the part is larger, or repeated in a way the object really
does repeat, and every element still has the shape and proportion image 1 gives
it. MORE of something is not a fault; a STRETCHED something is.

Answer UNSURE only if the pictures genuinely do not show enough to tell.

Reply with JSON and nothing else:

{{"verdict": "PASS" | "FAIL" | "UNSURE",
  "blame": "part" | "body",
  "why": "one sentence, naming what you actually see",
  "should_be": "{rules}"}}

"blame" says whether the fault is in the part itself or in the body around it.
"should_be" is required only when the verdict is FAIL and blame is "part": the
rule this part should have had instead. Use "fixed" if it should simply hold its
drawn size.
"""


def adaptations(prop_dir, face="front"):
    """Every decision worth auditing, with the reason the tool had for it."""
    d = Path(prop_dir)
    try:
        L = json.loads((d / f"layers_{face}.json").read_text())
        pj = json.loads((d / f"parts_{face}.json").read_text())
        sr = json.loads((d / "scale_rules.json").read_text())
    except Exception:
        return []
    try:
        strips = json.loads((d / f"strips_{face}.json").read_text())
    except Exception:
        strips = {}
    try:
        wide = {w["part"]: w for w in
                json.loads((d / "wide_art.json").read_text()).get("parts", [])
                if w.get("status") == "kept"}
    except Exception:
        wide = {}
    P = {p["name"]: p for p in pj.get("parts", [])}
    wx = float(sr.get("max_wider") or 1.0)
    hx = float(sr.get("max_taller") or 1.0)

    # THE AXIS COMES FROM THE RULE'S OWN PREFIX, not from which field it sits
    # in. `resize` and `resize_y` are two slots, and either can hold a spanx or
    # a spany rule -- v50's frame_left carries `spany_repeat` in `resize`, and
    # reading the slot rather than the value labelled it "across the prop" and
    # then described a horizontal band for a vertical rule. The enum says which
    # axis it is; the field only says where it was stored.
    def _axis(rule):
        return "wider" if rule.startswith("spanx") else (
            "taller" if rule.startswith("spany") else None)

    raw = []
    for q in L.get("parts", []):
        p = P.get(q["name"]) or {}
        why, axis = [], None
        for rule in (q.get("resize", "fixed"), q.get("resize_y", "fixed")):
            ax = _axis(rule)
            if not ax or ax == axis:
                continue
            axis = axis or ax
            where = "across the prop" if ax == "wider" else "down the prop"
            why.append(f"{where} it is `{rule}`")
            band = (q.get("bands") or {}).get("h" if ax == "wider" else "v")
            if q.get("lengthens") and ax == "taller":
                why.append("because the prop was said to get taller BY this "
                           "part -- a leg, column or upright that simply gets "
                           "longer")
            elif band:
                side = "width" if ax == "wider" else "height"
                why.append(f"because a uniform band was measured on it at "
                           f"{band[0]:.2f}..{band[1]:.2f} of its {side}, so its "
                           f"ends hold their drawn size and only that band "
                           f"repeats")
            elif ax == "wider" and q.get("hf"):
                why.append("because a plain flank was measured on it, and the "
                           "extra width is inserted there")
            else:
                why.append("with NO uniform band measured on it, so the whole "
                           "part is scaled")
        if p.get("per_bay") or p.get("per_tier"):
            which = "bay" if p.get("per_bay") else "tier"
            axis = axis or ("wider" if p.get("per_bay") else "taller")
            why.append(f"and it comes one per {which}, so a bigger prop is "
                       f"meant to have MORE of it rather than a bigger one")
        if q["name"] in wide:
            axis = "wider"
            w = wide[q["name"]]
            why.append(f"and because nothing uniform could be measured on it, "
                       f"{w.get('new_px')} pixels of extra artwork were "
                       f"GENERATED for its ends at {w.get('ratio')}x, with the "
                       f"drawn artwork composited back over the middle unchanged")
        if not why or not axis:
            continue
        raw.append({"part": q["name"], "axis": axis,
                    "scale": (wx if axis == "wider" else hx),
                    "did": ". ".join(w[0].upper() + w[1:] for w in why) + "."})

    # ONE DECISION IS ONE AUDIT, however many parts carry it. v50's nine
    # product windows are the SAME decision nine times -- "comes one per bay" --
    # and asking about each costs nine calls to learn one thing, then reports
    # one fault as nine. Identical reasoning on the same axis is grouped, the
    # largest member is the one rendered, and a verdict applies to all of them.
    out, seen = [], {}
    for r in raw:
        k = (r["axis"], r["did"])
        if k in seen:
            seen[k]["also"].append(r["part"])
            continue
        r["also"] = []
        seen[k] = r
        out.append(r)
    for r in out:
        if r["also"]:
            r["did"] += (f" {len(r['also']) + 1} parts on this prop carry the "
                         f"same decision ({', '.join([r['part']] + r['also'][:3])}"
                         f"{', ...' if len(r['also']) > 3 else ''}); this is "
                         f"one audit of all of them.")

    # the body's own adaptation, which is not a part and is the commonest fault
    gb = strips.get("grow_bands") or []
    H = (strips.get("size") or [1, 1])[1]
    if hx > 1.02:
        if gb:
            rows = sum(g["px"][1] - g["px"][0] for g in gb)
            places = ", ".join(
                f"rows {g['px'][0]}..{g['px'][1]}"
                + (f" (at the {g['side']} of {g['part']})"
                   if g.get("side") != "run" else " (found by measurement)")
                for g in gb)
            out.append({
                "part": "the body", "axis": "taller", "scale": hx, "only": None,
                "did": f"The carcass grows by INSERTING COPIES of its own "
                       f"artwork at {places} -- {rows} rows of a {H}-row "
                       f"elevation, chosen because nothing is drawn across "
                       f"them. Everything above and below a place holds its "
                       f"drawn size and simply moves apart."})
        else:
            out.append({
                "part": "the body", "axis": "taller", "scale": hx, "only": None,
                "did": "The carcass STRETCHES uniformly. Nowhere on this prop "
                       "is bare enough to insert copies of without repeating "
                       "something drawn, so the whole body is scaled instead."})
    return out


def shoot(prop_dir, adapts, out_dir, face="front"):
    """One browser session for every picture the audit needs."""
    d = Path(prop_dir)
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    rel = d.resolve().relative_to(ROOT)
    L = json.loads((d / f"layers_{face}.json").read_text())
    A = L["aspect"]
    box = {q["name"]: q for q in L["parts"]}
    qs, plan = [], []
    for a in adapts:
        q = box.get(a["part"])
        only = "" if a["part"] == "the body" else f"&only={a['part']}"
        for tag, w, h in (("one", 1, 1),
                          ("big", a["scale"] if a["axis"] == "wider" else 1,
                           a["scale"] if a["axis"] == "taller" else 1)):
            # AIM THE CAMERA AT THE PART, not at the machine. `?only=` hides the
            # other parts and still draws the whole body, so a coin slot's
            # "isolated" shot is a picture of a vending machine with one slot on
            # it -- and the model answers about the vending machine, which is
            # the exact failure this file exists to avoid. `?pan=` shifts the
            # look-at in frame-radius units, so the part can be framed.
            #
            # The frame is twice the part's own size, floored at an eighth of
            # the prop: a 9x13 coin slot filled to the edges is a picture of
            # nothing, and what "has it come away from what it is mounted on"
            # needs is the part WITH some of its surroundings.
            if q is None:
                frame = max(A * w, h) * 0.5 * 1.12
                pan = "0,0"
            else:
                pw = (q["u"][1] - q["u"][0]) * A * w
                ph = (q["v"][1] - q["v"][0]) * h
                # `frame` is the camera's HALF-height, so a part of size s wants
                # about 0.6s to fill the view with a margin -- 1.0s framed a
                # full-height rail at half the picture, which is zoomed OUT.
                # Floored at a fifth of the prop so a 9x13 coin slot comes with
                # enough of what it is mounted on to tell whether it still is.
                frame = max(max(pw, ph) * 0.6, max(A * w, h) * 0.20)
                cx = ((q["u"][0] + q["u"][1]) / 2 - 0.5) * A * w
                cy = ((q["v"][0] + q["v"][1]) / 2 - 0.5) * h
                pan = f"{cx / frame:.3f},{cy / frame:.3f}"
            qs.append(f"dir=/{rel}&w={w}&h={h}&frame={frame:.4f}"
                      f"&pan={pan}&yaw=18&pitch=8{only}")
            plan.append((a["part"], tag))
    if not qs:
        return {}
    import make_prop as M
    r = subprocess.run(["node", str(ROOT / "tools/authoring/parts_view/shoot.mjs"),
                        str(out), *qs], cwd=ROOT, env=M._env(),
                       capture_output=True, text=True, timeout=1800)
    if r.returncode != 0:
        print(f"  shoot failed: {(r.stderr or r.stdout or '')[-300:]}")
    # NAME THE FILE, DO NOT GUESS AT IT -- shoot.mjs derives the stem from the
    # query with one substitution, so the same substitution reproduces it
    # exactly. This first sorted the directory by modification time and zipped
    # it against the request order, which is the SAME class of error make_prop
    # records one screen up about globbing (`w-1-h-1` is a prefix of
    # `w-1-h-1-5`): the body's two shots carry no `only=` and land between the
    # parts', so every adaptation was judged against another one's pictures.
    # Three FAILs came back on pictures nobody had asked about.
    import re as _re
    got = {}
    for (name, tag), q in zip(plan, qs):
        p = out / (_re.sub(r"[^a-z0-9]+", "-", q, flags=_re.I) + ".png")
        if p.exists():
            got[(name, tag)] = p
    return got


def audit(prop_dir, asset, face="front", limit=None):
    from auto_prop import glm, as_json, data_uri, _openrouter_key, CRITIC_MODEL
    d = Path(prop_dir)
    adapts = adaptations(d, face)
    if limit:
        adapts = adapts[:limit]
    if not adapts:
        print("no resize or texture adaptation on this prop to audit")
        return []
    print(f"{len(adapts)} adaptation(s) to audit")
    shots = shoot(d, adapts, d / "_audit_resize", face)
    key = _openrouter_key()
    kit = d / "parts"
    rows = []
    for a in adapts:
        one = shots.get((a["part"], "one"))
        big = shots.get((a["part"], "big"))
        if not one or not big:
            print(f"  {a['part']:22} not rendered -- skipped")
            continue
        imgs = []
        drawn = kit / f"{a['part']}.png"
        if drawn.exists():
            imgs.append(drawn)
        elif (d / f"{face}.png").exists():
            imgs.append(d / f"{face}.png")
        imgs += [one, big]
        scale = (f"{a['scale']:g}x wider" if a["axis"] == "wider"
                 else f"{a['scale']:g}x taller")
        content = [{"type": "text",
                    "text": PROMPT.format(asset=asset, part=a["part"],
                                          did=a["did"], scale=scale,
                                          rules=" | ".join(RESIZES))}]
        for p in imgs:
            content.append({"type": "image_url",
                            "image_url": {"url": data_uri(p)}})
        try:
            reply = glm([{"role": "user", "content": content}],
                        CRITIC_MODEL, key, max_tokens=4000)
            v = as_json(reply)
        except Exception as e:
            print(f"  {a['part']:22} not audited ({type(e).__name__})")
            continue
        verdict = str(v.get("verdict", UNSURE)).upper()
        if verdict not in (PASS, FAIL, UNSURE):
            verdict = UNSURE
        blame = "body" if str(v.get("blame", "part")).lower() == "body" else "part"
        row = {"part": a["part"], "axis": a["axis"], "scale": a["scale"],
               "also": a.get("also") or [], "blame": blame,
               "verdict": verdict, "why": str(v.get("why", ""))[:400],
               "did": a["did"]}
        # A PART'S RULE IS ONLY PATCHED WHEN THE PART IS WHAT IS WRONG. The
        # price labels on v50's glass are in the BODY's texture, and at 2x they
        # smear while the product windows beside them hold their size -- a real
        # fault, and patching product_window_1 for it would change the one thing
        # in the picture that is behaving.
        if verdict == FAIL and blame == "part" and v.get("should_be") in RESIZES:
            row["should_be"] = v["should_be"]
        rows.append(row)
        mark = {PASS: "ok  ", FAIL: "FAIL", UNSURE: "?   "}[verdict]
        tag = "" if verdict != FAIL else f"[{blame}] "
        print(f"  {mark} {a['part']:22} {scale:12} {tag}{row['why'][:74]}")
    (d / "resize_audit.json").write_text(json.dumps(
        {"face": face, "adaptations": rows}, indent=1))
    n = sum(1 for r in rows if r["verdict"] == FAIL)
    print(f"audit: {len(rows)} judged, {n} FAIL, "
          f"{sum(1 for r in rows if r['verdict'] == UNSURE)} unsure")
    return rows


def faults(prop_dir, face="front"):
    """The failed audits, as the judge loop's fault-and-patch shape."""
    try:
        rows = json.loads(
            (Path(prop_dir) / "resize_audit.json").read_text())["adaptations"]
    except Exception:
        return [], []
    bad = [r for r in rows if r["verdict"] == FAIL]
    # A GROUPED VERDICT APPLIES TO EVERY PART THAT CARRIES THE DECISION. One
    # audit stands for all of them, so one FAIL patches all of them -- otherwise
    # the loop fixes the window that happened to be rendered and leaves eight
    # identical ones beside it.
    out, patch = [], []
    for r in bad:
        for n in [r["part"]] + (r.get("also") or []):
            out.append({"part": f"{n} (resize audit)", "severity": "blocking",
                        "fault": r["why"]})
            if r.get("should_be"):
                patch.append({"name": n, "resize": r["should_be"]})
    return out, patch


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("prop_dir")
    ap.add_argument("--asset", default="prop")
    ap.add_argument("--face", default="front")
    ap.add_argument("--limit", type=int)
    ap.add_argument("--report", action="store_true")
    args = ap.parse_args()

    if args.report:
        for a in adaptations(Path(args.prop_dir), args.face):
            print(f"  {a['part']:22} {a['axis']:7} {a['scale']:.2f}x")
            print(f"      {a['did'][:150]}")
        return
    audit(Path(args.prop_dir), args.asset, args.face, args.limit)


if __name__ == "__main__":
    main()
